

		-- PARETO LAW'S
		/* STEP 1. 고객 단위(customer_id)로 각 연도별 매출액 주문건수 집계하기 */
		SELECT	T.CUSTOMER_ID
			,	EXTRACT('YEAR' FROM T.TRAN_DATE)	AS YYYY
			,	COUNT(DISTINCT T.TRANSACTION_ID)	AS CNT_ORDER
			,	SUM(T.TOTAL_AMT)					AS SUM_AMT
		FROM	TRANSACTIONS AS T
		GROUP BY
				1, 2;
			
		/* STEP 2. 연도(yyyy) 단위로 전체 주문고객수, 매출액 집계 */
	WITH YEAR_TBL AS (
		SELECT	T.CUSTOMER_ID
			,	EXTRACT('YEAR' FROM T.TRAN_DATE)	AS YYYY
			,	COUNT(DISTINCT T.TRANSACTION_ID)	AS CNT_ORDER
			,	SUM(T.TOTAL_AMT)					AS SUM_AMT
		FROM	TRANSACTIONS AS T
		GROUP BY
				1, 2
				),
	TOT_TBL AS (
		SELECT	YYYY
			,	COUNT(DISTINCT	CUSTOMER_ID)		AS TOT_CUST
			,	SUM(SUM_AMT)						AS TOT_AMT
		FROM	YEAR_TBL
		GROUP BY
				1 )
		SELECT	*
		FROM	TOT_TBL;
	
		/* STEP 3. 연도별로 각 고객의 비중과 누적 비중을 구하기 */
	WITH YEAR_TBL AS (
		SELECT	T.CUSTOMER_ID
			,	EXTRACT('YEAR' FROM T.TRAN_DATE)	AS YYYY
			,	COUNT(DISTINCT T.TRANSACTION_ID)	AS CNT_ORDER
			,	SUM(T.TOTAL_AMT)					AS SUM_AMT
		FROM	TRANSACTIONS AS T
		GROUP BY
				1, 2
				),
	TOT_TBL AS (
		SELECT	YYYY
			,	COUNT(DISTINCT	CUSTOMER_ID)		AS TOT_CUST
			,	SUM(SUM_AMT)						AS TOT_AMT
		FROM	YEAR_TBL
		GROUP BY
				1
				)
		SELECT	YT.YYYY
			,	YT.CUSTOMER_ID
			,	1/CAST(TT.TOT_CUST AS FLOAT)			AS CUST_PROP
			,	SUM(1/CAST(TT.TOT_CUST AS FLOAT)) OVER(PARTITION BY YT.YYYY ORDER BY YT.SUM_AMT DESC)	AS ACC_CUST_PROP
			,	YT.SUM_AMT/CAST(TT.TOT_AMT AS FLOAT)	AS AMT_PROP
			,	SUM(YT.SUM_AMT/CAST(TT.TOT_AMT AS FLOAT)) OVER(PARTITION BY YT.YYYY ORDER BY YT.SUM_AMT DESC)	AS ACC_AMT_PROP
		FROM	YEAR_TBL AS YT
		JOIN
				TOT_TBL AS TT
		ON		YT.YYYY = TT.YYYY
		ORDER BY
				YYYY, AMT_PROP DESC
		;
		
	/*	Filter Query */
	
		/* 데이터베이스로 특정 구간(위치)의 누적 매출 비중 확인하는 쿼리 */
	WITH YEAR_TBL AS (
		SELECT	T.CUSTOMER_ID
			,	EXTRACT('YEAR' FROM T.TRAN_DATE)	AS YYYY
			,	COUNT(DISTINCT T.TRANSACTION_ID)	AS CNT_ORDER
			,	SUM(T.TOTAL_AMT)					AS SUM_AMT
		FROM	TRANSACTIONS AS T
		GROUP BY
				1, 2
				),
	TOT_TBL AS (
		SELECT	YYYY
			,	COUNT(DISTINCT	CUSTOMER_ID)		AS TOT_CUST
			,	SUM(SUM_AMT)						AS TOT_AMT
		FROM	YEAR_TBL
		GROUP BY
				1
				),
	FILTER_TBL AS (
		SELECT	YT.YYYY
			,	YT.CUSTOMER_ID
			,	1/CAST(TT.TOT_CUST AS FLOAT)			AS CUST_PROP
			,	SUM(1/CAST(TT.TOT_CUST AS FLOAT)) 
					OVER(PARTITION BY YT.YYYY ORDER BY YT.SUM_AMT DESC)	AS ACC_CUST_PROP
			,	YT.SUM_AMT/CAST(TT.TOT_AMT AS FLOAT)	AS AMT_PROP
			,	SUM(YT.SUM_AMT/CAST(TT.TOT_AMT AS FLOAT)) 
					OVER(PARTITION BY YT.YYYY ORDER BY YT.SUM_AMT DESC)	AS ACC_AMT_PROP
		FROM	YEAR_TBL AS YT
		JOIN
				TOT_TBL AS TT
		ON		YT.YYYY = TT.YYYY
				)
		SELECT	RN.*
		FROM	(
		SELECT	FT.*
			,	ROW_NUMBER() OVER(PARTITION BY FT.YYYY ORDER BY ACC_CUST_PROP DESC)	AS RN
		FROM	FILTER_TBL AS FT
		WHERE	FT.ACC_CUST_PROP <= 0.1
				) AS RN
		WHERE	RN.RN = 1;
		
	